### ISSUE TITLE
TypeError: countries.iso3 is undefined

### ISSUE THREAD

**Issue by acche** [wesbos/rona#12]
CountrySelector/<
./components/CountrySelector.js:24

  21 | >
  22 |   {Object.entries(countries.countries).map(([country, code]) => (
  23 |     <option
> 24 |       selected={selectedCountry === countries.iso3[code]}
     | ^  25 |       key={code}
  26 |       value={countries.iso3[code]}
  27 |     >

What did I missed?

**Comment by Dangandy** [comment]
the api has changed probably, this works
`          {Object.entries(countries.countries).map(
            ([_, { name: country, iso3: code }]) => (
              <option
                selected={selectedCountry === code}
                key={code}
                value={code}
              >
                {country}
              </option>
            )
          )}
`

**Comment by acche** [comment]
@Dangandy Got it, thanks.
