### ISSUE TITLE
Image not loading from covid api

### ISSUE THREAD

**Issue by erdahuja** [wesbos/rona#3]
Hi Wes,
I tried using the app and api. I wanted to add the dynamic image which is returned from this url.
`https://covid19.mathdro.id/api/og`

But this image is blocked by browser with CORB error.
It is an issue with the API?
they need to add CORS for this image api.

**Comment by pmareke** [comment]
This issue is not related to this repo, the problem is on the [API](https://github.com/mathdroid/covid-19-api), it would be better if you talk with the creator.
