### ISSUE TITLE
TypeError: Cannot read property '#<Object>' of undefined

### ISSUE THREAD

**Issue by Teegreat** [wesbos/rona#8]
Cannot read property of object In countrySelector.

It keeps highlighting "   selected={selectedCountry === countries.iso3[code]} "

**Comment by camargoltiago** [comment]
const [selectedCountry, setSelectedCountry] = useState('BRA');
  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error...</p>;

  let oldStructure = {
    countries: {},
    iso3: {}
  };

  for (let country of countries.countries) {
    oldStructure.countries[country.name] = country.iso2;
    oldStructure.iso3[country.iso2] = country.iso3;
  }

  return (
    <div>
      <h2>País Atual: {selectedCountry}</h2>

      <select
        onChange={e => {
          setSelectedCountry(e.target.value);
        }}
      >
        {Object.entries(oldStructure.countries).map(([country, code]) => (
          <option
            selected={selectedCountry === oldStructure.iso3[code]}
            key={code}
            value={oldStructure.iso3[code]}
          >
            {country}
          </option>
        ))}
      </select>
      <Stats
        url={`https://covid19.mathdro.id/api/countries/${selectedCountry}`}
      ></Stats>
    </div>
  );

**Comment by camargoltiago** [comment]
Just insert this:

  let oldStructure = {
    countries: {},
    iso3: {}
  };

  for (let country of countries.countries) {
    oldStructure.countries[country.name] = country.iso2;
    oldStructure.iso3[country.iso2] = country.iso3;
  }

And then :

 {Object.entries(oldStructure.countries).map(([country, code]) => (
          <option
            selected={selectedCountry === oldStructure.iso3[code]}
            key={code}
            value={oldStructure.iso3[code]}

**Comment by SauravKhare** [comment]
Now it's highlighting : **Cannot read property 'countries' of undefined**

`for (let country of countries.countries)`

**Comment by firebuggirl** [comment]
> Just insert this:
> 
> let oldStructure = {
> countries: {},
> iso3: {}
> };
> 
> for (let country of countries.countries) {
> oldStructure.countries[country.name] = country.iso2;
> oldStructure.iso3[country.iso2] = country.iso3;
> }
> 
> And then :
> 
> {Object.entries(oldStructure.countries).map(([country, code]) => (
> <option
> selected={selectedCountry === oldStructure.iso3[code]}
> key={code}
> value={oldStructure.iso3[code]}

Thank you @camargoltiago!

**Comment by firebuggirl** [comment]
Thank you @camargoltiago!

**Comment by camargoltiago** [comment]
Any time!

**Comment by kapilsipl** [comment]
Thanks @firebuggirl /@camargoltiago you are amazing!!!
I also resolved it, was updating the files but you posted before :)

Thanks

**Comment by Teegreat** [comment]
> Just insert this:
> 
> let oldStructure = {
> countries: {},
> iso3: {}
> };
> 
> for (let country of countries.countries) {
> oldStructure.countries[country.name] = country.iso2;
> oldStructure.iso3[country.iso2] = country.iso3;
> }
> 
> And then :
> 
> {Object.entries(oldStructure.countries).map(([country, code]) => (
> <option
> selected={selectedCountry === oldStructure.iso3[code]}
> key={code}
> value={oldStructure.iso3[code]}



Thanks for your reply. 
I'm still facing some challenges with the code.

**Comment by Teegreat** [comment]
> Thanks @firebuggirl /@camargoltiago you are amazing!!!
> I also resolved it, was updating the files but you posted before :)
> 
> Thanks

can I see how you solved it pls?

**Comment by kapilsipl** [comment]
> > Thanks @firebuggirl /@camargoltiago you are amazing!!!
> > I also resolved it, was updating the files but you posted before :)
> > Thanks
> 
> can I see how you solved it pls?

I update below code in CountrySelector.js
`
const [selectedCountry, setSelectedCountry] = useState('IND');
  if (loading) return <p>Loading...</p>;
  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error...</p>;

let newStructure = {
countries: {},
iso3: {}
};
for (let country of countries.countries) {

newStructure.countries[country.name] = country.iso2;
newStructure.iso3[country.iso2] = country.iso3;
}
  return (
    <div>
      <h2>Currently Showing {selectedCountry}</h2>
      <select
        onChange={e => {
          setSelectedCountry(e.target.value);}}>
        {Object.entries(newStructure.countries).map(([country, code]) => (
          <option
            selected={selectedCountry === newStructure.iso3[code]}
            key={code}
            value={newStructure.iso3[code]}>
            {country}
          </option>
        ))}
      </select>
      <Stats
        url={`https://covid19.mathdro.id/api/countries/${selectedCountry}`}
      ></Stats>
    </div>);}`

**Comment by kapilsipl** [comment]
@Teegreat I hope you find the solution, can you close this issue?

**Comment by Teegreat** [comment]
Thank you, everyone, for your contributions. I'm really grateful.

**Comment by katzcentrality** [comment]
Having trouble - maybe the API has changed again since?
