### ISSUE TITLE
where can i modify the interface !  

### ISSUE THREAD

**Issue by forloulhoucine** [wesbos/rona#9]

**Comment by SauravKhare** [comment]
Do you even know how to write code??

**Comment by forloulhoucine** [comment]
Yes i can.. I Just need too add a navbar with a logo and a side bar.. If u can guide me

**Comment by forloulhoucine** [comment]
> Do you even know how to write code??

Yes i can.. I Just need too add a navbar with a logo and a side bar.. If u can guide me

**Comment by wesbos** [comment]
The idea you are looking for here is called a layout component. Gatsby doesn't have any native layout tools, so you just use React components. Something like this:

https://github.com/wesbos/wesbos/blob/master/src/components/Layout.js

Or simple:

```js
function Layout({ children }) {
  return (
    <div>
      <nav>hi im in the nav</nav>
      {children}
</div>
  )
}
```

Then on every page (index.js in our case), wrap the page in `<Layout></Layout>`
